name: Continuous Integration (CI)
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  install:
    env:
      NPM_TOKEN: ${{'$'}}{{ secrets.SIB_NODE_PACKAGE_TOKEN }}

    name: 'Test & Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{'$'}}{{ secrets.SIB_NODE_PACKAGE_TOKEN }}
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci
      - name: 'Quality Checks'
        uses: DTSL/actions/js/quality-checks@v1
        with:
          GITHUB_TOKEN: ${{'$'}}{{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{'$'}}{{secrets.SONAR_TOKEN}}
